coyote-team/coyote

app/views/images/_form.html.haml

…database to prevent sync confusion; closes #94

Make Image title non-editable for images that have already been saved [closes #94]

---

lib/scavenger_hunt/app/controllers/scavenger_hunt/application_controller.rb

The issue is users trying to view games that do not belong to them - this should trigger a 404, but the way `current_player` was written caused it to return `false` instead of throwing an `ActiveRecord::RecordNotFound` error. This is a fix for that issue.

Force 404 rather than crashing on false from current_user

---

app/helpers/resources_helper.rb
app/models/representation.rb
app/models/resource.rb
app/views/representations/_audits.slim
app/views/representations/_form.html.slim
app/views/representations/show.html.slim
app/views/resources/_form.html.slim
app/views/resources/_representations.html.slim
db/migrate/20180825140356_add_ordinality_to_resources.rb
db/migrate/20180825140408_add_ordinality_to_representations.rb
db/structure.sql
spec/controllers/representations_controller_spec.rb
spec/controllers/resources_controller_spec.rb
spec/factories/representations.rb
spec/factories/resources.rb
spec/models/representation_spec.rb
spec/models/resource_spec.rb

Hey team! All I've done here (so far) is generate the ordinality columns on the resource and representation tables. Despite that it wasn't a bunch of work, I still wanted to create a pull request so that you could all keep a finger on the pulse and quickly point out if anything is off. I'll continue to add to this pull request as I complete the request for scoping by ordinality on the resources and representations. Thanks a million!

feat: add ordinality column to resources and representations

---

Procfile
app.json

This is cherry picked from the "streamlined deploy process" branch to ensure we _always_ run migrations when we push to Heroku.

Add a release phase for migrations

---

db/migrate/20180912004124_rename_clue_prompt_to_question.rb
db/structure.sql
lib/scavenger_hunt/app/models/scavenger_hunt/clue.rb
lib/scavenger_hunt/app/views/scavenger_hunt/answers/new.html.slim
spec/scavenger_hunt/models/game_spec.rb

These updates are not critical to the functionality of Coyote, but I had work time and @sinabahram mentioned removing all mentions of `prompt`. I think it would be awesome to have them all say `question` so that any new developer that joins the team will experience consistency. 
All Rspec tests for `game_spec.rb` are passing with the code in this first commit. 
I've gone through and updated most of the references to the `Scavenger Hunt: Question` that say `prompt` to say `question` instead. There are a few that I have not updated yet because they involve the database and I'm not sure if we should do those or not. If we do, I want to check first to make sure I don't mess things up.

fix: rename prompt with question for consistency

---

lib/scavenger_hunt/app/assets/stylesheets/scavenger_hunt/components/_input.sass
lib/scavenger_hunt/app/views/scavenger_hunt/answers/_form.html.slim

@flipsasser I used a global variable here to make the placeholder white. I put it in the `_input.sass`, but do you think it would be better in the css that's written in the `_location_styles.html.slim`? I can easily move it over there if you think that is better. I'm sure there are a bunch of ways to achieve this, so let me know if you think there is a better method. Thanks so much! 
**Update:** I just saw issue #216 which fits well on this feature branch. Anna wants the focus halo color to not be orange (there is probably a better name for it than focus halo...). I updated it to the blue global variable for $tint - that's a pretty standard focus color. BUT, just like any time I've touched styling so far in my VERY short dev career, I feel like I hacked it together. So, let me know if …

fix: update new answer input placeholder color and content, closes #215, closes #216

---

lib/scavenger_hunt/app/assets/stylesheets/scavenger_hunt/components/_input.sass
lib/scavenger_hunt/app/views/scavenger_hunt/answers/_form.html.slim

This is low priority. Just a one character update. 
In response to: _"This looks good. I'll say that you should double-check the modular CSS stuff I sent over - modifiers are typically separated by two hyphens instead of one, so an input .input that's inverted would be something like .input.input--inverted - that helps maintain the concept of "this is an input, but it also has a modifier applied to it" rather than what might read as "this is an input and also an input-inverted" - hopefully that makes sense"_
YES! OF COURSE! I had it as - in my head. Noted and updated! Thanks for all the excellent feedback @flipsasser!

fix: change - to -- on inverted modifier

---

lib/scavenger_hunt/app/assets/stylesheets/scavenger_hunt/components/_helper.sass
lib/scavenger_hunt/app/assets/stylesheets/scavenger_hunt/components/_typography.sass

This was a quick easy change to comply with accessibility requirements. I simply removed all css `text-transform: uppercase` from the Scavenger Hunt. Shouldn't require any feedback. Although, @alavatelliMCA will want to go through and let me know if there are any words that do need uppercase letters that didn't get them when coded. Like, "scavenger hunt"?

nix all uppercase in scavenger hunt, closes #224

---

lib/scavenger_hunt/app/assets/stylesheets/scavenger_hunt/components/_button.sass
lib/scavenger_hunt/app/views/scavenger_hunt/answers/_form.html.slim

Hi @flipsasser!
This took me way longer than I'll ever admit. So, before I spend any more time styling it, I wanted to see what you thought about the code. The button code that was there originally wasn't rendering a button in the view. So I tried a few different things and thought this looked the cleanest. I also added server-side validation because I was getting a params error when I'd try to submit with nothing in the text field (obvs.) 
1) What is the best way to do the button code here? How can I make my code better fit what is there? 
2) When it comes to styling, I need to make it appear like the `link_to game_clue_path(@game, @clue), class: "large"` but I think because I'm using the submit_tag, it's making it more like a button (really wide). So, I'm wondering if you know the best …

fix: render answer submit button in view - needs code review and styling

---

app/controllers/organizations_controller.rb
app/policies/organization_policy.rb
app/views/organizations/index.html.slim

**This PR allows the owner of an organization the ability to edit the organization by clicking the 'Edit' button on the organizations index view.** 
<hr>
I'm not super happy about the authorization line I added to the view, but followed Pundit's documentation to get it working. Ideally, I'd be able to call: 
```
- if policy(organization_user, org).edit? 
```
because you can call `policy` and pass through a user and a record then see if it is authorized to take an action. But, for some reason (that I could not figure out after an embarrassing amount of searching) the organization was not being passed through here and was resulting in Pundit returning a NilClass policy instead of OrganizationPolicy. So I had to use this line to instantiate a new instance and manually pass through the …

Add ability to edit organizations, closes #213

---

lib/scavenger_hunt/app/controllers/scavenger_hunt/players_controller.rb

Originally, this line: `redirect_to new_player_path unless current_player? && current_player.name.present?` was this: `redirect_to new_player_path unless current_player? && current_player.email.present?` I removed everything after `&&` because I thought, "oh, email isn't required and I shouldn't be hiding the show view from a player who has submitted all the required information". Then after testing Scavenger Hunt, I noticed I was never getting served the new player view realized, "duh, I'm never being `redirect_to` the `new_player_path` because the only code remaining was ensuring a current_player existed. Which it did. But I needed to have a current_player in existence AND that player must have a `name` present (which is the required field - whereas email is not).

require the player have a name present before rendering player show view

---

lib/scavenger_hunt/app/views/layouts/scavenger_hunt/_location_styles.html.slim

Per issue #216 we agreed that when the background is color, the input focus color should be white. That will ensure it is accessible with every organization's color choice (since the requirement for their choice is to be accessible with white).

change input focus on color background to white, closes #216

---

app/views/representations/_audits.slim

Ok, so there is still work to be done on this branch before it can close out any issues, but I wanted to get what I did pushed so that it could improve what is currently there. 
A while back, I was fixing some style issues on the audit log (displaying the tag style for values on the audit table), but to be honest, didn't understand the Audited library - or even know what it was and how it displayed. Anyway, I know more now and see that the tag styles I was applying didn't work with Audited. So this is basically restoring functionality so that the audit log shows the previous value and the updated value. 
It also includes a fix for this comment of Anna's "some columns display [nil, ""] as opposed to being blank". 
To fix this, we needed to set the default value of all text field attributes …

fix audits to display updated values

---

app/views/representations/index.html.slim

Ok, so the fix was to remove the `non-mobile-only` class from the toolbar-item. I cannot explain it, but that did the trick. So 2 questions: 
1. Any idea why that was messing it up? 
2. Can you think of a way we can still apply that class and not have it affect the functionality of the select all? 
@flipsasser

fix select all feature on representations view, closes #202

---

lib/scavenger_hunt/app/assets/stylesheets/scavenger_hunt/components/_helper.sass
lib/scavenger_hunt/app/controllers/scavenger_hunt/pages_controller.rb
lib/scavenger_hunt/app/views/layouts/scavenger_hunt/application.html.slim
lib/scavenger_hunt/app/views/scavenger_hunt/pages/about.html.slim
lib/scavenger_hunt/config/routes.rb

Hi @flipsasser! This static page is working, but I have a few questions on how I can refactor the code. Since we're on a time crunch I didn't want to spend too much time on it and if I don't hear back from you within the next hour, I am going to go ahead and merge it (since it's not broken code or anything) and I'll create an issue about refactoring it. 
**First thing:** I tried to get the route and pages#show method to be dynamic. Meaning work with something like this in the route: ` get "/pages/:page" => "pages#show"
`and this in the show method: `render template: "pages/#{params[:page]}"` but I couldn't get it working in the engine, so I just made it explicit. Do you have thoughts on how/if I should do that? 
**Second thing:** I've got some sass that could be cleaned up, but can't seem …

create about page for scavenger hunt, closes #310

---

app/controllers/api/users_controller.rb
app/serializers/serializable_membership.rb
app/serializers/serializable_user.rb
spec/api/users_spec.rb

This PR adds organisation membership information as relationship and included record to the API `/profile` endpoint's response: 
```json
{
"data": {
"id": "7",
"type": "user",
"attributes": {
"first_name": "Misti",
"last_name": "Metz"
},
"relationships": {
"organizations": {
"data": [
{
"type": "organization",
"id": "1"
}
]
},
"memberships": {
"data": [
{
"type": "membership",
"id": "5"
}
]
}
}
},
"included": [
{
"id": "1",
"type": "organization",
"attributes": {
"name": "Acme Museum"
}
},
{
"id": "5",
"type": "membership",
"attributes": {
"active": true,
"first_name": "Misti",
"last_name": "Metz",
"email": "admin@example.com",
"role": "admin",
"organization_id": "1"
}
}
],
"jsonapi": {
"version": "1.0"
}
}
```

Include membership information within /profile API response

---

config/database.yml

The database configuration used `ENV.fetch()` to get the `DATABASE_URL` environment variable, this throws a `KeyError` when the ENV key does not exist. In production this variable is not used, hence attempting to bring up the server would throw a `KeyError`. This PR uses the `ENV["DATABASE_URL"]` syntax instead, which silently defaults to `Nil`.

Replace ENV.fetch() by ENV[] to get DATABASE_URL config variable

---

config/appsignal.yml

Appsignal only runs in staging/production mode, hence this wasn't caught in development or test (and is a symptom that should be addressed).

Hotfix for appsignal configuration parsing

---

app/views/layouts/application.html.slim

We're not tracking any errors yet, so to have it initialising in the footer is not necessary.

Remove Appsignal front-end initialisation

---

app/models/organization.rb
db/migrate/20220725061155_alter_organizations_unique_name_index.rb
db/schema.rb
spec/factories/organizations.rb
spec/models/organization_spec.rb

Organizations were previously indexed on their unique name; this caused an index constraint error when "Acme Museum" was deleted and then recreated. This partial index resolves this such that multiple deleted organizations with the same name can exist, but only a single "Acme Museum" that is not deleted can only ever exist.
This addresses #593.

Add partial organizations index on unique name when not deleted.

---

app/controllers/resources_controller.rb
app/helpers/filter_helper.rb
app/serializers/serializable_resource.rb
lib/coyote/helpers/production_config_helper.rb
spec/lib/coyote/helpers/production_config_helper_spec.rb
spec/serializers/serializable_resource_spec.rb

This closes #670 by including the resource's `host_uris` property within its `attributes` list.

Include host uris in serialised resource

---

Gemfile
Gemfile.lock
app/controllers/resources_controller.rb
app/helpers/filter_helper.rb
app/workers/notify_webhook_worker.rb
lib/coyote/helpers/production_config_helper.rb
spec/lib/coyote/helpers/production_config_helper_spec.rb
spec/models/resource_spec.rb
spec/support/webhook_context.rb

This closes #657. 
Webhook redirects for HTTP 301, 302 and 303 should not be followed as the `Location` header target should only respond to a GET. This raises a custom exception for debugging and logging purposes.
HTTP 307 should be handled properly (by issuing the same request to its `Location` target.

Faraday handles HTTP redirect responses

---

app/assets/stylesheets/elements/_resources.sass
app/controllers/resources_controller.rb
app/helpers/filter_helper.rb
app/models/resource.rb
app/views/resources/show.html.slim
db/migrate/20221215104530_alter_resources_unique_source_uri_index.rb
db/schema.rb
lib/coyote/helpers/production_config_helper.rb
spec/controllers/resources_controller_spec.rb
spec/factories/resources.rb
spec/lib/coyote/helpers/production_config_helper_spec.rb
spec/models/resource_spec.rb

This closes #664 by allowing duplicate `organization_id` and `source_uri` columns with differing `is_deleted` values.

Do not constrain resource source_uri when identical uri resource is soft-deleted

---

docker-compose-production.yml

This work modifies `docker-compose-production.yml` to add a volume to the Postgres container so the database persists between taking containers down and spinning them back up. This Allows Coyote to be reliably taken down and spun up using `docker-compose -f docker-compose-production.yml down/upp`

Add DB volume to production compose file
